const pool = require("../config/db");

// ----------------------------------------
// GENERATE COMPLAINT
// ----------------------------------------

const generateComplaint = async ({
  investigationId
}) => {
  try {
    // --------------------------------
    // Get investigation + registration
    // --------------------------------

    const result = await pool.query(
      `
      SELECT
        i.*,
        g.pan,
        g.business_name,
        g.business_sector,
        g.ip_address,
        g.location,
        g.risk_score,
        g.freeze_reason
      FROM investigations i
      JOIN gst_registrations g
        ON g.id = i.registration_id
      WHERE i.id = $1
      `,
      [investigationId]
    );

    if (result.rows.length === 0) {
      throw new Error(
        "Investigation not found"
      );
    }

    const investigation = result.rows[0];

    // --------------------------------
    // Generate complaint text
    // --------------------------------

    const complaintText = `
GST FRAUD ALERT / COMPLAINT

Subject:
Suspected unauthorized GST registration using PAN ${investigation.pan}

Registration Details:
GST Registration ID: ${investigation.registration_id}
Business Name: ${investigation.business_name}
Business Sector: ${investigation.business_sector}
Registration Location: ${investigation.location}

Risk Details:
Risk Score: ${investigation.risk_score}
Risk Level: HIGH

Security Event:
The PAN holder was alerted about the GST registration attempt and explicitly denied authorizing the registration.

Citizen Response:
NO

Freeze Action:
The GST registration has been frozen.

Freeze Reason:
${investigation.freeze_reason}

Technical Information:
IP Address: ${investigation.ip_address}

Requested Action:
Please investigate the suspected unauthorized GST registration and take appropriate action according to the applicable GST verification and fraud-handling procedures.

This complaint was automatically generated by GSTSecureX PAN Watch.
`.trim();

    // --------------------------------
    // Save complaint
    // --------------------------------

    const updateResult = await pool.query(
      `
      UPDATE investigations
      SET
        complaint_text = $1,
        updated_at = NOW()
      WHERE id = $2
      RETURNING *
      `,
      [
        complaintText,
        investigationId
      ]
    );

    if (updateResult.rows.length === 0) {
      throw new Error(
        "Complaint could not be saved"
      );
    }

    console.log(
      `📝 Complaint generated for investigation ${investigationId}`
    );

    return updateResult.rows[0];

  } catch (error) {
    console.error(
      "❌ Complaint service failed:",
      error.message
    );

    throw error;
  }
};

module.exports = {
  generateComplaint
};